package javaswingdev.form;

import My_Classes.User;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.lang.reflect.Method;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javaswingdev.main.Main;
import javaswingdev.form.ThanhTraCH;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author Nguyễn Văn Khoa
 */
public class CaNhan extends javax.swing.JFrame {

    /**
     * Creates new form MembersListForm
     */
    My_Classes.Func_Class func = new My_Classes.Func_Class();
    My_Classes.User user = new My_Classes.User();
    String imagePath = "";
    byte[] displayImage = null;
    int ur_user_id;

    public CaNhan(int users_id) {
        ur_user_id = users_id;
        initComponents();

        this.setLocationRelativeTo(null);

        Border panelHeaderBorder = BorderFactory.createMatteBorder(3, 3, 3, 3, new Color(252, 231, 125));
        jPanel1.setBorder(panelHeaderBorder);

        //display image        
        func.displayImage(70, 70, null, "/My_Images/icons8_male_user_100px.png", jLabel_Form_Title);

        //border the image
        Border JlaBorder = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_Image1.setBorder(JlaBorder);

        //add a default image
        func.displayImage(230, 230, null, "/My_Images/icons8_male_user_500px.png", jLabel_Image1);

        //display the book infor
        displayMemberInfor(users_id);
    }

    //creat a func to display the book infor
    public void displayMemberInfor(int users_id) {
        try {
            System.out.println(users_id);
            My_Classes.User selectedUsers = user.getMemberByIdInCaNhanFrame(users_id);

            if (selectedUsers != null) {
                jTextField1_ID_User.setText(String.valueOf(selectedUsers.getId()));
                jTextField2_FullName.setText(selectedUsers.getFullname());
                jTextField2_Phone.setText(selectedUsers.getPhone());
                jTextField2_Email.setText(selectedUsers.getEmail());
                jTextField2_Quequan.setText(selectedUsers.getEmail());
                jTextField5_UserName.setText(selectedUsers.getTaikhoan());
               
                jTextField3_Pass.setText(selectedUsers.getMaukhau());
                jTextField4_Role.setText(selectedUsers.getRole());
                if (Integer.parseInt(selectedUsers.getGender()) == 1) {
                    jTextField2_gender.setText("NAM");
                } else {
                    jTextField2_gender.setText("NỮ");
                }

                //display image:
                byte[] image = selectedUsers.getPicture();
                //we will display the image using the imagebyte
                //so we will made the image path null
                displayImage = image;
                func.displayImage(300, 290, image, "", jLabel_Image1);
            } else {

            }
        } catch (SQLException ex) {
            Logger.getLogger(CaNhan.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Image = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel_Form_Title = new javax.swing.JLabel();
        jLabel_Close = new javax.swing.JLabel();
        jLabel_Image1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1_ID_User = new javax.swing.JTextField();
        jTextField2_FullName = new javax.swing.JTextField();
        jTextField3_Pass = new javax.swing.JTextField();
        jTextField4_Role = new javax.swing.JTextField();
        jTextField5_UserName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2_Phone = new javax.swing.JTextField();
        jLabel_ImagePath = new javax.swing.JLabel();
        jButton_Select_Picture = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField2_Email = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField2_Quequan = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField2_gender = new javax.swing.JTextField();
        jLabel_FirstName7 = new javax.swing.JLabel();

        jLabel_Image.setBackground(new java.awt.Color(204, 204, 255));
        jLabel_Image.setOpaque(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_Form_Title.setBackground(new java.awt.Color(53, 53, 53));
        jLabel_Form_Title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_Form_Title.setForeground(new java.awt.Color(109, 180, 50));
        jLabel_Form_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Form_Title.setText("CÁ NHÂN");
        jLabel_Form_Title.setOpaque(true);

        jLabel_Close.setBackground(new java.awt.Color(53, 53, 53));
        jLabel_Close.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel_Close.setForeground(new java.awt.Color(109, 180, 50));
        jLabel_Close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Close.setText("X");
        jLabel_Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Close.setOpaque(true);
        jLabel_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseClicked(evt);
            }
        });

        jLabel_Image1.setBackground(new java.awt.Color(249, 97, 103));
        jLabel_Image1.setOpaque(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Tài khoản:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Họ tên:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("ID:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Chức vụ:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Mật khẩu:");

        jButton1.setBackground(new java.awt.Color(53, 53, 53));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(108, 180, 50));
        jButton1.setText("Xác nhận");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1_ID_User.setEditable(false);
        jTextField1_ID_User.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jTextField2_FullName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jTextField3_Pass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jTextField4_Role.setEditable(false);
        jTextField4_Role.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jTextField5_UserName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField5_UserName.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("SĐT:");

        jTextField2_Phone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel_ImagePath.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel_ImagePath.setForeground(new java.awt.Color(109, 180, 50));
        jLabel_ImagePath.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_ImagePath.setText("Ảnh đại diện");

        jButton_Select_Picture.setBackground(new java.awt.Color(102, 102, 102));
        jButton_Select_Picture.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Select_Picture.setForeground(new java.awt.Color(109, 180, 50));
        jButton_Select_Picture.setText("Chọn ảnh");
        jButton_Select_Picture.setContentAreaFilled(false);
        jButton_Select_Picture.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Select_Picture.setOpaque(true);
        jButton_Select_Picture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Select_PictureActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Email:");

        jTextField2_Email.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Quê quán:");

        jTextField2_Quequan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Giới tính:");

        jTextField2_gender.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel_FirstName7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_FirstName7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_Form_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_Image1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField2_gender)
                                    .addComponent(jTextField2_Quequan)
                                    .addComponent(jTextField2_Email)
                                    .addComponent(jTextField1_ID_User)
                                    .addComponent(jTextField2_FullName)
                                    .addComponent(jTextField2_Phone)
                                    .addComponent(jTextField3_Pass)
                                    .addComponent(jTextField4_Role, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField5_UserName)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_ImagePath, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton_Select_Picture, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(63, 63, 63)))
                                .addGap(43, 43, 43)
                                .addComponent(jLabel_FirstName7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 369, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Close, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Form_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Close, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_Image1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_ImagePath)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Select_Picture, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1_ID_User, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2_FullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2_Quequan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField5_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField3_Pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField4_Role, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel_FirstName7)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel_CloseMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if ("".equals(jTextField2_FullName.getText()) || "".equals(jTextField2_Phone.getText())
                || "".equals(jTextField5_UserName.getText()) || "".equals(jTextField3_Pass.getText()) || "".equals(jTextField2_Email.getText())
                || "".equals(jTextField2_Quequan.getText()) || "".equals(jTextField2_gender.getText())) {
            JOptionPane.showMessageDialog(null, "Những trường trên không được bỏ trống", "Error", 1);
        } else {
            byte[] img = null;
            int gender;
            int id = Integer.parseInt(jTextField1_ID_User.getText());
            String fullname = jTextField2_FullName.getText();
            String phone = jTextField2_Phone.getText();
            String quequan = jTextField2_Quequan.getText();
            String email = jTextField2_Email.getText();
            String password = jTextField3_Pass.getText();
            String role = jTextField4_Role.getText();
            if ("NAM".equalsIgnoreCase(jTextField2_gender.getText())) {
                gender = 1;
            } else {
                gender = 0;
            }

            if (imagePath != null && displayImage == null) {
                try {
                    Path path = Paths.get(imagePath);
                    if (Files.size(path) > (1024 * 1024)) {
                        JOptionPane.showMessageDialog(null, "Kích cỡ ảnh không hợp lệ ! ", "Lỗi Ảnh", 0);
                        return;
                    }
                    img = Files.readAllBytes(path);
                    user.editMember(id, fullname, email, phone, quequan, gender, img, password, role);
                    javaswingdev.main.Main.displayNameAndAvatar(fullname);

                } catch (IOException | SQLException ex) {
                    Logger.getLogger(EditUser.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else if (displayImage != null) {
                try {
                    user.editMember(id, fullname, email, phone, quequan, gender, displayImage, password, role);
                   
                    javaswingdev.main.Main.displayNameAndAvatar(fullname);
                } catch (SQLException ex) {
                    Logger.getLogger(EditUser.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Select a profile picture for this member", "no picture selected", 0);
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton_Select_PictureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Select_PictureActionPerformed
        //select pictuer from the PC

        String path = func.selectImage();
        jLabel_ImagePath.setText(path);

        //display the image when we select in path
        func.displayImage(240, 177, null, path, jLabel_Image1);
//         byte[] image = null;
//        try {
//            image = user.getPictureOfMember(ur_user_id);
//        } catch (SQLException ex) {
//            Logger.getLogger(CaNhan.class.getName()).log(Level.SEVERE, null, ex);
//        }
        displayImage =  null;
        imagePath = path;
//        displayMemberInfor(ur_user_id);
    }//GEN-LAST:event_jButton_Select_PictureActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_Select_Picture;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Close;
    private javax.swing.JLabel jLabel_FirstName7;
    private javax.swing.JLabel jLabel_Form_Title;
    private javax.swing.JLabel jLabel_Image;
    private javax.swing.JLabel jLabel_Image1;
    private javax.swing.JLabel jLabel_ImagePath;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1_ID_User;
    private javax.swing.JTextField jTextField2_Email;
    private javax.swing.JTextField jTextField2_FullName;
    private javax.swing.JTextField jTextField2_Phone;
    private javax.swing.JTextField jTextField2_Quequan;
    private javax.swing.JTextField jTextField2_gender;
    private javax.swing.JTextField jTextField3_Pass;
    private javax.swing.JTextField jTextField4_Role;
    private javax.swing.JTextField jTextField5_UserName;
    // End of variables declaration//GEN-END:variables

}
